on: push
name: Continuous Integration
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Cache dialyzer plts
        uses: actions/cache@v4.1.2
        with:
          path: priv/plts
          key: ${{runner.os}}-${{hashFiles('**/.tool-versions')}}-plts

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: ".tool-versions"
          version-type: "strict"

      - name: Deps get and check unused
        run: mix deps.get && mix deps.unlock --check-unused
      - name: Check Credo
        run: mix credo --strict
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Run Tests
        run: mix do compile --warnings-as-errors, test
      - name: Dialyzer
        run: mix dialyzer
